name: syllable
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  html: any
  flashy_flushbar: any
  archive: ^3.6.1
  shared_preferences: any
  path_provider: any
  file_picker: ^8.1.3
  #syncfusion_flutter_pdf: any

dev_dependencies:
  flutter_launcher_icons: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  #    flutter pub run flutter_launcher_icons:main
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  fonts: 
    - family: JetBrainsMono
      fonts:
        - asset : fonts/JetBrainsMono.ttf

    - family: Departure
      fonts:
        - asset : fonts/Departure.otf

    - family: Haxorville
      fonts:
        - asset : fonts/Haxorville.ttf

    - family: OpeningHoursMono
      fonts:
        - asset : fonts/OpeningHoursMono.ttf

    - family: RobotoMono
      fonts:
        - asset : fonts/RobotoMono.ttf

    - family: YukiCode
      fonts:
        - asset : fonts/YukiCode.otf

  assets:
    - assets/translations/
