name: syllable
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  html: any
  archive: any
  shared_preferences: any
  file_picker: any
    #syncfusion_flutter_pdf: any

dev_dependencies:
  flutter_launcher_icons: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  #    flutter pub run flutter_launcher_icons:main
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  fonts: 
    - family: JetBrainsMono
      fonts:
        - asset : fonts/JetBrainsMono-Regular.ttf
